# Generated by Django 4.2.3 on 2023-07-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('especie', models.CharField(choices=[('Cac', 'Cachorro'), ('Gat', 'Gato'), ('Pas', 'Passaro'), ('Cav', 'Cavalo')], default='Cac', max_length=3)),
                ('nome_dono', models.CharField(max_length=50)),
                ('numero_dono', models.CharField(max_length=12)),
            ],
        ),
    ]
